### PR TITLE
Update config format

### PR DESCRIPTION
**Pull request by abtris**
- `PAGERDUTY_READ_ONLY_TOKEN` is used for read schedules and check them.
- `SCHEDULES` array can contains one or more `SCHEDULE` to check
- every `SCHEDULE` have `PAGERDUTY_TOKEN` to create incident if overlap is found

```json
{
	"PAGERDUTY_API_URL": "https://acme.pagerduty.com/api/v1",
	"PAGERDUTY_READ_ONLY_TOKEN": "33333333333333333333",
	"SCHEDULES": [{
		"SCHEDULE": ["PWEVPB6", "PT57OLG"],
		"NOTIFICATIONS": {
			"PAGERDUTY_TOKEN": "11111111111111111111"
		}
	}, {
		"SCHEDULE": ["PWEVPB6", "PT57OLA"],
		"NOTIFICATIONS": {
			"PAGERDUTY_TOKEN": "22222222222222222222"
		}
	}]
}
```
- **TODO: notifications not work**

### CODE REVIEW

**Comment by abtris** [comment]
@nadade It's ready to merge.

**Comment by nadade** [comment]
@abtris shouldn't node_modules be in .gitignore?

**Comment by nadade** [comment]
@abtris how do I configure the time interval for checking?

**Comment by nadade** [comment]
@abtris otherwise - good to go :+1:

**Comment by abtris** [comment]
@nadade comments addressed

**Pull request merged**
